{% set name = "tobler" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8aac24aeb963151eb31cee6f24e6b9a83f7fc9ae0d4b92f08d7716308861ede9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=61.0
    - setuptools-scm >=6.2
  run:
    - python >={{ python_min }}
    - pandas
    - numpy >=1.16
    - geopandas >=0.13
    - rasterio
    - rasterstats
    - statsmodels
    - scipy
    - libpysal >=4.2.0
    - tqdm
    - joblib

test:
  requires:
    - python {{ python_min }}
  imports:
    - tobler

about:
  home: https://github.com/pysal/tobler
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Tobler is a python package for areal interpolation, dasymetric mapping, and change of support.
  description: |
    Tobler is a python package for areal interpolation, dasymetric mapping, and change of support.
  doc_url: https://pysal.org/tobler/
  dev_url: https://github.com/pysal/tobler/

extra:
  recipe-maintainers:
    - knaaptime
    - sjsrey
    - martinfleis
    - jGaboardi
